[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pi3"
version = "0.1"
description = "pi3"
readme = "README.md"
requires-python = ">=3.10.0"
dependencies = [
    "safetensors",
]

# Setuptools configuration
[tool.setuptools]
# Disable automatic package discovery to avoid conflicts
packages = ["pi3"]

# Include package data
[tool.setuptools.package-data]
"pi3" = ["**/*"]

[tool.ruff]
line-length = 120
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501", "E402", "E731", "E722", "E741", "E721", "E701", "F841", "F403", "F405", "F821"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
